// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubTask(arg1, arg2) {
  return window['go']['main']['App']['AddSubTask'](arg1, arg2);
}

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DetectBackgroundLuminance() {
  return window['go']['main']['App']['DetectBackgroundLuminance']();
}

export function ForceBackup() {
  return window['go']['main']['App']['ForceBackup']();
}

export function GetLastBackupTime() {
  return window['go']['main']['App']['GetLastBackupTime']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function IsAlwaysOnTop() {
  return window['go']['main']['App']['IsAlwaysOnTop']();
}

export function OnWindowBlur() {
  return window['go']['main']['App']['OnWindowBlur']();
}

export function OnWindowFocus() {
  return window['go']['main']['App']['OnWindowFocus']();
}

export function ReorderTasks(arg1, arg2) {
  return window['go']['main']['App']['ReorderTasks'](arg1, arg2);
}

export function ToggleAlwaysOnTop() {
  return window['go']['main']['App']['ToggleAlwaysOnTop']();
}

export function ToggleExpanded(arg1) {
  return window['go']['main']['App']['ToggleExpanded'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
