// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSubTask(arg1:number,arg2:string):Promise<main.Task>;

export function AddTask(arg1:string):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function DetectBackgroundLuminance():Promise<main.BackgroundLuminance>;

export function GetTasks():Promise<Array<main.Task>>;

export function GetWindowState():Promise<main.WindowState>;

export function IsAlwaysOnTop():Promise<boolean>;

export function OnWindowBlur():Promise<void>;

export function OnWindowFocus():Promise<void>;

export function ReorderTasks(arg1:Array<number>,arg2:any):Promise<void>;

export function ToggleAlwaysOnTop():Promise<void>;

export function ToggleExpanded(arg1:number):Promise<void>;

export function UpdateTask(arg1:main.Task):Promise<void>;
